worlds:
  ignored: true
  valid: []
head:
  steal-on-sell: false
  broadcast-sell: false
  drop-worthless: true
  worthless-value: 0
  player-kills-only: true
  give-to-top-hunter: false
  drop-spawner-mobs: true
  drop-projectiles: true
  drop-fire-damage: true
  format:
    value: '&eHead Value'
    bounty: '&eBounty'
    worthless: '&r&c&oWorthless'
bounty:
  minimum-value: 20
  place-cooldown: 300
  broadcast-place: true
  broadcast-claim: true
enchantments:
  looting-effect: 0.08
  smite-effect: 0.05
factions:
  drop-in-wilderness: true
  drop-in-safezone: false
  drop-in-warzone: false
  drop-in-faction: false
  friendly-kills: false